### ISSUE TITLE
[FEATURE REQUEST] Please add MP3 to AT3 conversion

### ISSUE THREAD

**Issue by Jimmm** [XyLe-GBP/ATRACTool-Reloaded#2]
It will help a lot, my whole collection is mp3.

**Comment by XyLe-GBP** [comment]
If you want to convert mp3, you need to convert it to wave once on the tool.
You need to use 'Tool'->'AudioConverter'->'Audio to WAVE' to convert, and then convert the wave to at3 or at9.
In the future, we plan to implement a function to convert directly to at3 or at9.

**Comment by XyLe-GBP** [comment]
With this update, the following formats can be read directly.
(mp3, m4a, aac, flac, alac, aiff, wma, ogg, opus)
Thus, the need to convert from an 'Tool'->'AudioConverter' has been eliminated.
After loading, a conversion window will appear and you can convert according to your target console. After that, the converted Wave will be loaded directly.
Enjoy :D

**Comment by Jimmm** [comment]
Wow, thanks a lot  XyLe-GBP!
One question: I drag n drop an mp3 file, choose psp, convert ... wav is created and loaded, but psp format isn*t chosen. I have to choose one more time. 
Bonus question: why is portable version 4 times smaller?

**Comment by XyLe-GBP** [comment]
Thanks for the report.
This will be fixed in the next update.
The reason the portable version has less space is because it does not incorporate the net6 runtime.
The lack of the runtime will result in a smaller footprint.
The portable version requires the net6 runtime to be installed from Microsoft's page instead of the smaller capacity. (In the portable version, the application itself cannot be launched without the runtime installed.)
The release version is larger but does not require the net6 runtime to be installed.

**Comment by XyLe-GBP** [comment]
Thanks for the report.
This will be fixed in the next update.
The reason the portable version has less space is because it does not incorporate the net6 runtime.
The lack of the runtime reduces the size of the application.
The portable version requires the net6 runtime to be installed from the Microsoft page. (In the portable version, the application itself cannot be launched without installing the runtime.)
The release version has a larger capacity than the portable version, but does not require the net6 runtime to be installed because the runtime is already embedded in the application. In other words, instead of being larger, the release version does not require the net6 runtime to be installed on the PC in order to run.
If you already have the net6 runtime installed, it is worth using the portable version to save space.

**Comment by XyLe-GBP** [comment]
This update corrects the file so that the appropriate console is selected when the file is converted.
If you have problems, please leave a comment again.
